language: java

jdk:
  - oraclejdk8

env:
  global:
     - GH_REF: github.com/hscells/hscells.github.io.git
     - GH_TOKEN: XXqxidH/NKflladdsfKNyqRhNe0fUm6zz6bxMnmEnjFo3RJIXFI4r0vLMQLRQEWnF+Aj1zmn283RN72/0MlmfZ0EsJbocVAi6D6XAUFU3Tm1eQyRNLnf+8bo0otwn5OamDLmRz/KmIVvtEC1ouo/Q1wJReUur6SzQQitO/M1zdk=
     - secure: XXqxidH/NKflladdsfKNyqRhNe0fUm6zz6bxMnmEnjFo3RJIXFI4r0vLMQLRQEWnF+Aj1zmn283RN72/0MlmfZ0EsJbocVAi6D6XAUFU3Tm1eQyRNLnf+8bo0otwn5OamDLmRz/KmIVvtEC1ouo/Q1wJReUur6SzQQitO/M1zdk=

before_script:
 - cd src
 - javac *.java
 - cd ../
 - git config --global user.email "harryscells@gmail.com"
 - git config --global user.name "Travis-CI"
 - git config --global push.default matching

after_script:
 - git clone https://github.com/hscells/hscells.github.io.git
 - javadoc -private src/*.java -d hscells.github.io/INB334/doc -bottom "Harry Scells 2015 INB334" > /dev/null 2>&1
 - cd hscells.github.io
 - git add *
 - git commit -m "updated INB334 javadoc"
 - git push --force "https://${GH_TOKEN}@${GH_REF}"
