trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_stopword_stemming -Dterrier.index.prefix=data -Dtrec.model=TF_IDF -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_stopwords_stemmer_TF_IDF.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery
trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_stopwords -Dterrier.index.prefix=data -Dtrec.model=TF_IDF -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_stopwords_TF_IDF.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery
trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_none -Dterrier.index.prefix=data -Dtrec.model=TF_IDF -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_none_TF_IDF.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery

trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_stopword_stemming -Dterrier.index.prefix=data -Dtrec.model=LemurTF_IDF -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_stopwords_stemmer_LemurTF_IDF.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery
trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_stopwords -Dterrier.index.prefix=data -Dtrec.model=LemurTF_IDF -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_stopwords_LemurTF_IDF.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery
trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_none -Dterrier.index.prefix=data -Dtrec.model=LemurTF_IDF -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_none_LemurTF_IDF.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery

trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_stopword_stemming -Dterrier.index.prefix=data -Dtrec.model=Tf -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_stopwords_stemmer_Tf.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery
trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_stopwords -Dterrier.index.prefix=data -Dtrec.model=Tf -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_stopwords_Tf.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery
trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_none -Dterrier.index.prefix=data -Dtrec.model=Tf -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_none_Tf.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery

trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_stopword_stemming -Dterrier.index.prefix=data -Dtrec.model=BB2 -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_stopwords_stemmer_BB2.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery
trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_stopwords -Dterrier.index.prefix=data -Dtrec.model=BB2 -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_stopwords_BB2.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery
trec_terrier.sh -r -Dterrier.index.path=/Users/harryscells/terrier-4.0/var/index_none -Dterrier.index.prefix=data -Dtrec.model=BB2 -Dtrec.results.file=/Users/harryscells/Repositories/INB344/src/week6/ap8889_none_BB2.txt -Dtrec.topics=/Users/harryscells/terrier-4.0/share/TREC123.topics.51-200.short.full.clean.txt -Dtrec.topics.parser=SingleLineTRECQuery
